### ISSUE TITLE
请教一下，我想配置一个用于其他应用开发而不是laravel，该怎么修改网站根目录不是public？

### ISSUE THREAD

**Issue by PonyTang3** [RystLee/DevDock#1]
就是根目录是public外层的文件夹

**Comment by iMacken** [comment]
@Tang1024 这个项目本来就不是针对laravel的，我习惯把DevDock放在我的工作区里，然后Docker会自动映射我工作区所有的项目到容器中。

**Comment by PonyTang3** [comment]
@RystLee 哦，这个配置还没用过，因为之前都在用laradock，在PHPhub看到，过来看了看，以为也是针对laravel。
