### ISSUE TITLE
请问一下php-worker和php-workspace是什么？

### ISSUE THREAD

**Issue by co8bit** [RystLee/DevDock#10]
谢谢~~

**Comment by co8bit** [comment]
我找到了，是运行容器后访问8080端口是吗？但是我用localhost  root  root登录的时候提示：#2002 - Can't connect to local MySQL server through socket '/run/mysqld/mysq

**Comment by iMacken** [comment]
所有需要填写 host 的地方一律填写应用名称 ，如 mysql, redis ...
