### ISSUE TITLE
装好后不能执行 404 目录好像不对

### ISSUE THREAD

**Issue by meilunzhi** [RystLee/DevDock#2]
server_name laravel.app;

    root /var/www/laravel/public;
    
    index index.php index.html index.htm;

    location / {
         try_files $uri $uri/ /index.php$is_args$args;
    }

进入docker 后的目录 

/var/www/laravel/public

root@3eb093c21707:/var/www/laravel/public# ls
index.php
root@3eb093c21707:/var/www/laravel/public#

访问的结果是404

**Comment by RystLee** [comment]
@Denniskevin 做一下 host 映射就好了 ：127.0.0.1   laravel.app ，抱歉这么晚回复你，这个项目我打算继续维护下去，谢谢支持。
