### ISSUE TITLE
Unsupported config option for services service: 'phpmyadmin'

### ISSUE THREAD

**Issue by lincome** [RystLee/DevDock#3]
执行：docker-compose up -d nginx mysql后报错：
Unsupported config option for services service: 'phpmyadmin'
是什么问题呢

**Comment by iMacken** [comment]
@lincome 升级下 docker 试一试

**Comment by lincome** [comment]
![Uploading 微信截图_20170417172916.png…](docker跟composer的版本)

**Comment by lincome** [comment]
[找到答案了](http://stackoverflow.com/questions/36724948/docker-compose-unsupported-config-option-for-services-service-webl)，好像是docker-composer 版本不对

**Comment by icescrown** [comment]
tianon/true是什么镜像？

**Comment by iMacken** [comment]
@bug12138 超轻量容器 用来单独装载 application code
