### ISSUE TITLE
请求流程是怎么样的？

### ISSUE THREAD

**Issue by ghost** [RystLee/DevDock#4]
docker小白不太懂，整个请求的流程是不是像下面这样的？  
client->nginx->php-fpm->workspace(php-cli)->php-fpm->nginx->client

如果是的话，php-fpm->workspace(php-cli)->php-fpm 这几步流程是具体怎么实现的，是走端口吗？ 看了laradock的workspace里面有个crontab的文件 跑了这个命令 php /var/www/artisan  这个应该是内置的服务器吧， 是不是通过这个连接了php-fpm和workspace两个容器？

**Comment by iMacken** [comment]
和正常的开发环境没太大区别，我们通过ip和端口映射与之进行通信。容器之间如果需要通信，link一下即可。你通过观察 docker-compose.yml文件就能研究个大概。
