### ISSUE TITLE
rm: cannot remove '/var/lib/apt/lists/*': No such file or directory

### ISSUE THREAD

**Issue by ZhouLiHai** [RystLee/DevDock#8]
在Mac上部署docker时出现一个问题：

```
rm: cannot remove '/var/lib/apt/lists/*': No such file or directory
ERROR: Service 'php-fpm' failed to build: The command '/bin/sh -c rm -r /var/lib/apt/lists/*' returned a non-zero code: 1
```

google之后发现：

> 终端出现: 'E:Encountered a section with no Package: header, E:Problem with MergeList /var/lib/apt/lists/archive.canonical.com_dists_maverick_partner_binary-i386_Packages, E:无法解析或打开软件包的列表或是状态文件。'
解决方法,终端执行：
```
    sudo rm -rf /var/lib/apt/lists/* -vf
    sudo apt-get update
```
看样子只有在apt出问题时才会使用这个方法，如果想要一个干净的环境 `rm -rf /var/lib/apt/lists/` 这个方式可能解决这个问题。

另:

```
docker --version
Docker version 17.06.0-ce, build 02c1d87
```

**Comment by iMacken** [comment]
thx. I've updated the relevant file.
